### ISSUE TITLE
JWT

### ISSUE THREAD

**Issue by 413n** [specialtactics/laravel-api-boilerplate#13]
I'm writing here not because there is an issue, but just for know a thing that keeps me blocked.
I'm pretty new to JWT, and while building all the databases and understanding this beautiful boilerplate you created, I got stuck while trying to authenticate for get a token.
I created a User in a separated method, then I tried to login using Postman putting the Accept header and the Basic Auth with the credentials but always got the error "Token has expired".
I tried debugging the error for a couple of hours and still don't know where I'm wrong.
If you can help me I will be so grateful. Thanks

**Comment by specialtactics** [comment]
Hey @hwmb there is an example collection and environment in the docs/ directory of the repo. I would recommend you import both of those into postman, then make sure you update the HOST env variable based on whatever your local setup is, and begin using those.

There is an Auth folder with an auth route, and that gives you an idea of how the auth should work, and hopefully that will give you enough info.

The more technical explanation is that you need to do a get request to the token route, with an auth header, where the value of the header is `Basic <string>` where the `<string>` is a base64 encoded string of the username, then a colon, then a password. So expressing it in PHP, it would be:

```php
authString = base64_encode($username . ':' . $password);
```

And the username in Laravel is generally (by default anyway) the email of the "User", and you would provide the password in plaintext there.

**Comment by 413n** [comment]
I got really thank you for the support and the amazing boilerplate you created! It saves alot of time from reinventing the wheel.
I don't know why yesterday it was giving me that error but know that I recloned the repo and pushed the changes, it works and it's great!
Thanks @specialtactics !

**Comment by specialtactics** [comment]
Awesome, great to hear !
