### ISSUE TITLE
what happens after generate the controller and model?

### ISSUE THREAD

**Issue by leandroruel** [specialtactics/laravel-api-boilerplate#15]
i generated the controllers and models using the artisan command recommended at docs, but I noticed that the UserController does not have an index, show, update and delete methods but they still works under the hood anyway, I looked at `routes/api.php`, and saw all methods in a different pattern like get, getAll, put, path and delete using HTTP terms, my question is, those methods are auto-generated automatically after generating the controller?

**Comment by leandroruel** [comment]
nevermind, now i give a close look at the base controller and found those methods

**Comment by leandroruel** [comment]
i give a close look at the BaseController and found the methods get, getAll...

**Comment by specialtactics** [comment]
Yep, they are in the RestfulController in the l5-api package. They follow the HTTP method naming convention.
