### ISSUE TITLE
display errors

### ISSUE THREAD

**Issue by leandroruel** [specialtactics/laravel-api-boilerplate#16]
how i should return error messages it has anything documented about that? like, i'm doing a function to return followers  and in my UserController i return just: 
```json
{
 "error": "you can't follow yourself"
}
```

any pattern?

**Comment by specialtactics** [comment]
Hi @leandroruel 

Basically just throw the relevant http exception with whatever message you want. There are many HTTP exceptions in Symphony's http kernel, and some more in Dingo.

Have a look at boilerplate code, there are plenty of examples in the controllers.

**Comment by leandroruel** [comment]
thank you, found it! shared this repo in my twitter too

**Comment by specialtactics** [comment]
Awesome, thanks @leandroruel ! :smile:
