### ISSUE TITLE
[BUG] All links in wiki "Table of Contents" are not accessible

### ISSUE THREAD

**Issue by connecteev** [specialtactics/laravel-api-boilerplate#23]
All links in wiki "Table of Contents" are not accessible
https://github.com/specialtactics/laravel5-api-boilerplate/wiki

Examples:
https://github.com/specialtactics/l5-api-boilerplate/wiki/Generators
https://github.com/specialtactics/l5-api-boilerplate/wiki/Validation

Not a huge issue since clicking on "pages" works fine, but thought I'd let you know

**Comment by specialtactics** [comment]
Hi there, thanks for reporting!

The Generators link needed to be updated, I've done that now. Validation actually does not exist, that's why it's not accessible. I will create a placeholder page for it to remove the confusion.

**Comment by connecteev** [comment]
Awesome, sounds good :) thanks for the quick turn

**Comment by specialtactics** [comment]
No worries, also I will put in place some docs for validation this week. Good to see someone's reading the docs!

For now, validation revolves around the getValidationRules() function, which is actually documented in "getting started" anyway.
