### ISSUE TITLE
Named routes not working using dingo api router

### ISSUE THREAD

**Issue by sunder6218** [specialtactics/laravel-api-boilerplate#25]
Hey,

im moving my current project into Api using this boiler plate, and i have noticed that my laravel named routes dont work when using the dingo APi router.

`$api->get('/dashboard', 'PagesController@dashboard')->name('dashboard2');`

then i get this error from the controller

`Route [dashboard2] not defined.`

is there a particular reason why this is happening?

thanks

**Comment by specialtactics** [comment]
Hi

Can you please try the following syntax:

```php
$api->get('/dashboard', [
    'uses' => 'PagesController@dashboard',
    'as' => 'dashboard2',
]);
```

Also, what exactly are you doing in the controller to get that error?

**Comment by specialtactics** [comment]
Closing due to lack of feedback in a month.

If you still have this issue, feel free to let me know - but also, probably you actually should submit it in the dingo repo.
