### ISSUE TITLE
[BUG] 'id' in response got unset if $primaryKey in Model set to 'id'

### ISSUE THREAD

**Issue by JT501** [specialtactics/laravel-api-boilerplate#26]
**Version Information**
PHP Version: 7.3
Package Version (l5-api): 1.0.3

**Describe the bug**
The Primary got unset in response.

**To Reproduce**
Set $primaryKey = 'id' in Model.
Return response using BaseTransformer.

**Expected behavior**
Data with primary key.

**Additional context**
nope

I managed to find out the bug in `RestfulTransformer.php`.
```php
 /**
  * Primary Key transformation - all PKs to be called "id"
  */
 $transformed = array_merge(
        ['id' => $model->getKey()],
        $transformed
);
unset($transformed[$model->getKeyName()]);
```

I added if condition to check if the primary key equal to 'id' or not, before the unset action.
```php
 /**
  * Primary Key transformation - all PKs to be called "id"
  */
 $transformed = array_merge(
        ['id' => $model->getKey()],
        $transformed
);
if ($model->getKeyName() != 'id') {
        unset($transformed[$model->getKeyName()]);
}
```

**Comment by JT501** [comment]
I have submitted a pull request to l5-api

**Comment by specialtactics** [comment]
Thanks for reporting! I will check out the PR

**Comment by specialtactics** [comment]
Merged, thanks !
