### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by codeace** [specialtactics/laravel-api-boilerplate#32]
**Version Information**
PHP Version: 7.3
Package Version (l5-api): 1.0

**Describe the bug**
Unable to use with laravel nova. Nova Login page just refresh when the correct credentials are supplied.

**To Reproduce**
1. Install laravel nova
2. Try to login to Nova

**Expected behavior**
Should be able to login with the correct credentials

**Additional context**
Looks like there is a conflict with between the nova route and dingo

**Comment by specialtactics** [comment]
Hey @codeace thanks for reporting.

Sorry but, I can't consider it as a bug if it's just an incompatibility between an external dependency and a third party package.

The more appropriate place to report this might be in the dingo repo - but even so, I think it's actually just a matter of configuration, for how to integrate the two packages correctly.

If you are willing to do the work, let us know the outcome, and I will document it if anyone else is interested.
