### ISSUE TITLE
Routing access

### ISSUE THREAD

**Issue by libaowei924** [specialtactics/laravel-api-boilerplate#33]
I installed this project, but didn't my interface routing add an API after the address? Why can't you access it?

**Comment by specialtactics** [comment]
Hey @libaowei924 

Sorry but I can't quite understand the issue, can you please describe in more detail?

**Comment by libaowei924** [comment]
Should I add an API after the link? Such as http://laravel-api-boilerplate.test/api/home

**Comment by libaowei924** [comment]
Should I add an API after the link? Such as http://laravel-api-boilerplate.test/api/home

404 no matter how I access it

**Comment by libaowei924** [comment]
@specialtactics

**Comment by libaowei924** [comment]
Only docker?

**Comment by specialtactics** [comment]
Hi, how are you sending these messages? I Cannot find on github
