### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by k2gsalem** [specialtactics/laravel-api-boilerplate#35]
on creating a new user with the role return 500 Internal Server Error with 
"message": "Return value of App\\Entities\\User::getStoredRole() must implement interface Spatie\\Permission\\Contracts\\Role, null returned",
how to solve this issue

**Comment by specialtactics** [comment]
Hey, it seems like the issue you are having is with an unrelated package, not any related to this boilerplate.

**Comment by k2gsalem** [comment]
sorry wrong package
