### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Eolykab** [specialtactics/laravel-api-boilerplate#43]
**Version Information**
PHP Version: 
Package Version (l5-api): 

**Describe the bug**
I am getting an error when trying to setup docker. 
configure: error: Package requirements (oniguruma) were not met:

No package 'oniguruma' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables ONIG_CFLAGS
and ONIG_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

**To Reproduce**
When I run docker-compose up
**Expected behavior**

**Additional context**

**Comment by specialtactics** [comment]
Hey @Eolykab 

Would I be correct to say you are trying to compile PHP 7.4 image ?

**Comment by Eolykab** [comment]
Yes correct

**Comment by specialtactics** [comment]
Hey @Eolykab , I will update the boilerplate to make PHP 7.4 default (for some reason I thought this was already the case)

Meanwhile, to fix this I think all you need to do is add this to the list of packages being installed at the top of the Dockerfile of the "php-fpm" and "workspace "containers (inside env/docker)

`
    libonig-dev \
`

**Comment by Eolykab** [comment]
Works like a charm. Thanks

**Comment by specialtactics** [comment]
tagged as v2.0.3
