### ISSUE TITLE
Does not support php8.0？

### ISSUE THREAD

**Issue by xinfox-ltd** [specialtactics/laravel-api-boilerplate#60]
composer create-project

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - specialtactics/l5-api[v3.0.0-beta1, ..., v3.0.1] require php ^7.3 -> your php version (8.0.3) does not satisfy that requirement.
    - Root composer.json requires specialtactics/l5-api ^3.0 -> satisfiable by specialtactics/l5-api[v3.0.0-beta1, v3.0.0, v3.0.1].

**Comment by specialtactics** [comment]
Hey there, I think it's easier to add PHP 8 support with laravel 9, the main reason is that there are upstream repos that are not compatible with php 8, I think the jwt-auth, however that was taken over recently by a new php group, so I will take a look to see if I can do it with the current version of the boilerplate.

**Comment by specialtactics** [comment]
Hey @xinfox-ltd PHP 8 support has been added to the dependency package.
