### ISSUE TITLE
[F-REQ] SSL Support

### ISSUE THREAD

**Issue by abikali** [specialtactics/laravel-api-boilerplate#61]
I'm currently using this boilerplate to host an api, and linked to a domain name api.example.com.

I need to serve the domain through ssl but it seems the docker-compose file only supports port 80? Would I need to edit the nginx config files in order to make it run over HTTPS? my domain is under cloudflare

**Comment by specialtactics** [comment]
Hey @abikali this is more of an infrastructure question, the docker setup which comes with the boilerplate is purely for local usage.

How you set up your infrastructure for SSL is up to you, but it's not related to this boilerplate, or even Laravel itself.

You can for sure google for help on this topic and nginx configs, but it's just very outside of the scope of this project, so I cannot help you with that here.
