### ISSUE TITLE
problem with current test unit

### ISSUE THREAD

**Issue by Master-maynd** [specialtactics/laravel-api-boilerplate#65]
with mysql it composer test gives an error
Error in bootstrap script: Illuminate\Database\QueryException:
SQLSTATE[08006] [7] received invalid response to SSL negotiation: Y (SQL: select tablename from pg_catalog.pg_tables where schemaname in ('public'))

**Comment by Master-maynd** [comment]
when testing sqllite is set to memory this code
`$console->call('migrate:fresh', ['--seed' => true]);`
 in he bootstrap file does not create the tables and all db tests fail. Kindly help

**Comment by specialtactics** [comment]
Hey @Master-maynd that error is a postgres error, I think you haven't changed your local setup properly to MySQL if you are intending to use that.
