### ISSUE TITLE
Suggest to use

### ISSUE THREAD

**Issue by lloricode** [specialtactics/laravel-api-boilerplate#7]
data layer https://github.com/andersao/l5-repository
acl https://github.com/spatie/laravel-permission
 @specialtactics :+1:

**Comment by lloricode** [comment]
if it possible also to add laravel passport?

**Comment by lloricode** [comment]
i have a lumen version https://github.com/lloricode/lumen-dingo-boilerplate with dingo

**Comment by specialtactics** [comment]
Thanks for the suggestions @lloricode !

I think the repository package will be quite incompatible with what this boilerplate does.

I'll have a look at the permissions package and think about the best way to integrate it. Currently this boilerplate already has roles, and you can specify permissions using the laravel policies, which is a pretty standard way to go. I think any extension to this will be in the next version of the boilerplate.

In terms of passport, in my experience having passport and dingo work together is somewhat problematic, however it is definitely my plan to use passport in the future. Very roughly, I think it will require a rewrite of dingo and/or a decoupling of this boilerplate from dingo to do this well.

**Comment by lloricode** [comment]
@specialtactics :100:
