### ISSUE TITLE
Got Error transform() must be an instance of Specialtactics\\L5Api\\Transformers\\Object, instance of stdClass given

### ISSUE THREAD

**Issue by minkbear** [specialtactics/laravel-api-boilerplate#9]
Using version https://github.com/specialtactics/laravel5-api-boilerplate/commit/241d8f198eaa5d9418e12fb10ca02576004e3d79

ERROR

`Argument 1 passed to Specialtactics\\L5Api\\Transformers\\RestfulTransformer::transform() must be an instance of Specialtactics\\L5Api\\Transformers\\Object, instance of stdClass given, called in /var/www/job/vendor/league/fractal/src/Scope.php on line 407`

DEBUG INFO
File: /var/www/job-api-server/vendor/specialtactics/l5-api/src/Transformers/RestfulTransformer.php
Line: 23

Please advice.

**Comment by minkbear** [comment]
fix at https://github.com/specialtactics/l5-api/blob/3a172f27f8a50130e6794373c826ceda5b9719d5/src/Transformers/RestfulTransformer.php#L23

from

`public function transform(Object $object)`

to

`public function transform($object)`

**Comment by specialtactics** [comment]
Hi @minkbear I think you are actually not using it correctly.

What gets passed to the transformer should always be an object. Dingo wise, if you return an item it will be the eloquent model, and if its a collection it will be an eloquent collection. Alternatively, you can create an std class with arbitrary data, but that is generally not what you would do for APIs.

Can you explain more what you are trying to do, and maybe add some code from the controller?

**Comment by minkbear** [comment]
@specialtactics 
Thank you for yous awsome boilerplate, It saves my times a lot.

I just downloaded your laravel5-api-boilerplate (revision https://github.com/specialtactics/laravel5-api-boilerplate/commit/241d8f198eaa5d9418e12fb10ca02576004e3d79) without modify anything.
and try to access http://my.api/auth/jwt/token then I got the error.

So my AuthController.php is the same as https://github.com/specialtactics/laravel5-api-boilerplate/blob/master/app/Http/Controllers/Auth/AuthController.php

**More info**

- PHP = 7.1
- dingo/api = 2.1.0

Please advice.

**Comment by specialtactics** [comment]
Hey there @minkbear 

Thanks, after re-reading that error and looking at your PHP version I've realised what's happened, which is that the code actually requires PHP 7.2, and you are running 7.1. I have changed it slightly to make it backwards compatible with 7.1 and pushed the change (but not tagged it yet).

Can you please try this locally and tell me if that fixes your issue?
https://github.com/specialtactics/l5-api/commit/4e3edf58950cecfb19412ba0b5ba3dbd9ea82fed

Thanks

**Comment by minkbear** [comment]
Hi @specialtactics 

Your code (https://github.com/specialtactics/l5-api/commit/4e3edf58950cecfb19412ba0b5ba3dbd9ea82fed)  fix my issue. no error anymore.

Thank you.

**Comment by specialtactics** [comment]
Great @minkbear I've tagged that as 0.0.10 now.
